import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ title }) {
  return (
    <>
      <Head>
        <title>Events APP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <img src="" alt="" />
          <a href="/">Home</a>
          <a href="/events">Events</a>
          <a href="/about-us">About US</a>
        </nav>
      </header>
      <main className={styles.main}>
        <a href="">
          <img />
          <h2>Event in London</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus
            obcaecati natus sed labore fugiat facere autem dicta id in
            consequuntur. Vitae quam nostrum esse et animi numquam ut cupiditate
            maxime.
          </p>
        </a>
        <a href="">
          <img />
          <h2>Event in San Francisco</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus
            obcaecati natus sed labore fugiat facere autem dicta id in
            consequuntur. Vitae quam nostrum esse et animi numquam ut cupiditate
            maxime.
          </p>
        </a>
        <a href="">
          <img />
          <h2>Event in Barcelona</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus
            obcaecati natus sed labore fugiat facere autem dicta id in
            consequuntur. Vitae quam nostrum esse et animi numquam ut cupiditate
            maxime.
          </p>
        </a>
      </main>
      <footer className={styles.footer}>
        <p>2022 Time to Code - A project on NextJS</p>
      </footer>
    </>
  )
}

export function getServerSideProps() {
  return {
    props: {
      title: 'Hello EveryOne!'
    }
  }
}
